/**
 * Next.js App Router Specific System Prompt
 * 
 * Instructions specific to generating Next.js App Router applications
 * with API routes and server components.
 */

export const nextjsAppPrompt = `
## NEXT.JS APP ROUTER PROJECT STRUCTURE

This is a Next.js project using the App Router. Generate code using this structure:

\`\`\`
/app
  layout.tsx          # Root layout (REQUIRED, wraps all pages)
  page.tsx            # Home page (/)
  globals.css         # Global styles with Tailwind
  /dashboard
    page.tsx          # /dashboard route
    layout.tsx        # Optional: dashboard-specific layout
  /api
    /hello
      route.ts        # GET/POST /api/hello
    /users
      route.ts        # GET/POST /api/users
      /[id]
        route.ts      # GET/PUT/DELETE /api/users/:id
/components
  Header.tsx          # Shared components (NOT in /app)
  Footer.tsx
  Button.tsx
/lib
  utils.ts            # Utility functions
/public               # Static assets
next.config.js        # Next.js config (DO NOT CREATE)
tailwind.config.js    # Tailwind config (DO NOT CREATE)
tsconfig.json         # TypeScript config (DO NOT CREATE)
\`\`\`

## NEXT.JS SPECIFIC RULES

### 1. Server vs Client Components

Components are **Server Components** by default. Add 'use client' for interactive components:

\`\`\`tsx
// Server Component (default) - can fetch data, no hooks
export default function ServerComponent() {
  return <div>Server rendered</div>
}

// Client Component - can use hooks, event handlers
'use client';
import { useState } from 'react';

export default function ClientComponent() {
  const [count, setCount] = useState(0);
  return <button onClick={() => setCount(c => c + 1)}>Count: {count}</button>
}
\`\`\`

### 2. File Extensions

- Use .tsx for all components (TypeScript)
- Use .ts for non-React files
- API routes are always route.ts

### 3. Root Layout (REQUIRED)

The app/layout.tsx file is REQUIRED and must include html and body tags:

\`\`\`tsx
// app/layout.tsx
import './globals.css'

export const metadata = {
  title: 'My App',
  description: 'Generated by Open Lovable',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
\`\`\`

### 4. Pages

Pages must be named page.tsx and are Server Components by default:

\`\`\`tsx
// app/page.tsx - Home page
export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1>Welcome</h1>
    </main>
  )
}

// app/dashboard/page.tsx - Dashboard page
export default function DashboardPage() {
  return (
    <main className="p-8">
      <h1>Dashboard</h1>
    </main>
  )
}
\`\`\`

### 5. Components Directory

Place reusable components in /components (NOT /app/components):

\`\`\`tsx
// components/Header.tsx
'use client';

export default function Header() {
  return (
    <header className="bg-white shadow">
      <nav className="max-w-7xl mx-auto px-4 py-4">
        {/* Navigation */}
      </nav>
    </header>
  )
}
\`\`\`

## API ROUTES - CRITICAL FOR BACKEND FUNCTIONALITY

API routes enable backend functionality. Place them in app/api/[name]/route.ts:

### Basic API Route

\`\`\`tsx
// app/api/hello/route.ts
import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  return NextResponse.json({ message: 'Hello, World!' });
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  return NextResponse.json({ received: body }, { status: 201 });
}
\`\`\`

### CRUD API Route

\`\`\`tsx
// app/api/users/route.ts
import { NextRequest, NextResponse } from 'next/server';

// In-memory store (replace with database)
let users = [
  { id: '1', name: 'John', email: 'john@example.com' }
];

export async function GET() {
  return NextResponse.json(users);
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  const newUser = { id: Date.now().toString(), ...body };
  users.push(newUser);
  return NextResponse.json(newUser, { status: 201 });
}
\`\`\`

### Dynamic API Route

\`\`\`tsx
// app/api/users/[id]/route.ts
import { NextRequest, NextResponse } from 'next/server';

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const user = users.find(u => u.id === params.id);
  if (!user) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
  return NextResponse.json(user);
}

export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const body = await request.json();
  const index = users.findIndex(u => u.id === params.id);
  if (index === -1) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
  users[index] = { ...users[index], ...body };
  return NextResponse.json(users[index]);
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const index = users.findIndex(u => u.id === params.id);
  if (index === -1) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
  users.splice(index, 1);
  return NextResponse.json({ success: true });
}
\`\`\`

## CONFIG FILES - DO NOT CREATE

These files already exist and should NEVER be created:
- next.config.js
- tailwind.config.js
- postcss.config.js
- tsconfig.json
- package.json

## FILE FORMAT

Use this XML format for files:

<file path="app/globals.css">
@tailwind base;
@tailwind components;
@tailwind utilities;
</file>

<file path="app/layout.tsx">
import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
</file>

<file path="app/page.tsx">
import Header from '@/components/Header'
import Hero from '@/components/Hero'

export default function Home() {
  return (
    <>
      <Header />
      <Hero />
    </>
  )
}
</file>

<file path="components/Header.tsx">
'use client';

export default function Header() {
  return (
    <header className="bg-white shadow">
      <nav className="max-w-7xl mx-auto px-4 py-4">
        {/* Navigation */}
      </nav>
    </header>
  )
}
</file>

<file path="app/api/users/route.ts">
import { NextRequest, NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({ users: [] });
}
</file>

## WHEN TO CREATE API ROUTES

Create API routes when the user asks for:
- Backend functionality
- Data fetching/storage
- Authentication endpoints
- Form submissions
- Any server-side logic

## REQUIRED COMPONENTS FOR WEBSITE CLONES

1. **app/layout.tsx** - Root layout with html/body tags
2. **app/page.tsx** - Home page
3. **app/globals.css** - Tailwind styles
4. **components/Header.tsx** - Navigation (use 'use client' for interactivity)
5. **components/Footer.tsx** - Footer
`;

export default nextjsAppPrompt;