/**
 * Next.js App Router Project Type Configuration
 * 
 * This project type enables full-stack Next.js applications with
 * App Router, API routes, and server components.
 */

import type { ProjectTypeConfig, ProjectTypeFile } from '../project-type';

// Entry files for Next.js App Router
const entryFiles: ProjectTypeFile[] = [
  {
    path: 'app/layout.tsx',
    content: `import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sandbox App',
  description: 'Generated by Open Lovable',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`
  },
  {
    path: 'app/page.tsx',
    content: `export default function Home() {
  return (
    <main className="min-h-screen bg-gray-900 text-white flex items-center justify-center p-4">
      <div className="text-center max-w-2xl">
        <h1 className="text-4xl font-bold mb-4">Next.js Sandbox Ready</h1>
        <p className="text-lg text-gray-400">
          Start building your Next.js app with App Router and API Routes!
        </p>
      </div>
    </main>
  )
}`
  },
  {
    path: 'app/globals.css',
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
}`
  },
  {
    path: 'app/api/hello/route.ts',
    content: `import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json({ message: 'Hello from API!' })
}

export async function POST(request: Request) {
  const body = await request.json()
  return NextResponse.json({ received: body }, { status: 201 })
}`
  }
];

// Config files for Next.js App Router
const configFiles: ProjectTypeFile[] = [
  {
    path: 'package.json',
    content: JSON.stringify({
      name: 'sandbox-nextjs-app',
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        next: '^14.0.0'
      },
      devDependencies: {
        typescript: '^5.0.0',
        '@types/react': '^18.2.0',
        '@types/node': '^20.0.0',
        tailwindcss: '^3.4.0',
        postcss: '^8.4.0',
        autoprefixer: '^10.4.0'
      }
    }, null, 2)
  },
  {
    path: 'next.config.js',
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    serverActions: true,
  },
}

module.exports = nextConfig`
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'es5',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./*'] }
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules']
    }, null, 2)
  },
  {
    path: 'tailwind.config.js',
    content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
  },
  {
    path: 'postcss.config.js',
    content: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
  }
];

export const nextjsAppConfig: ProjectTypeConfig = {
  id: 'nextjs-app',
  name: 'Next.js (App Router)',
  description: 'Full-stack Next.js with App Router, API routes, and server components',
  
  // File structure
  sourceDir: 'app',
  componentsDir: 'components',
  pagesDir: 'app',
  apiDir: 'app/api',
  publicDir: 'public',
  
  // Build configuration
  devCommand: 'npm run dev',
  buildCommand: 'npm run build',
  devPort: 3000,
  startupDelay: 15000, // Next.js takes longer to start than Vite
  
  // Dependencies
  baseDependencies: {
    'react': '^18.2.0',
    'react-dom': '^18.2.0',
    'next': '^14.0.0'
  },
  
  baseDevDependencies: {
    'typescript': '^5.0.0',
    '@types/react': '^18.2.0',
    '@types/node': '^20.0.0',
    'tailwindcss': '^3.4.0',
    'postcss': '^8.4.0',
    'autoprefixer': '^10.4.0'
  },
  
  // Entry files
  entryFiles,
  configFiles,
  
  // Path transformation - convert Vite-style paths to Next.js structure
  filePathTransform: (path: string): string => {
    if (path.startsWith('/')) path = path.slice(1);
    
    // Skip config files
    const configFileNames = ['package.json', 'next.config.js', 'tailwind.config.js', 'postcss.config.js', 'tsconfig.json'];
    if (configFileNames.includes(path)) {
      return path;
    }
    
    // Don't transform paths already in correct locations
    if (path.startsWith('app/') || path.startsWith('components/') || path.startsWith('public/') || path.startsWith('lib/')) {
      return path;
    }
    
    // Transform Vite-style component paths
    if (path.startsWith('src/components/')) {
      return path.replace('src/components/', 'components/');
    }
    
    // Transform src/ to app/
    if (path.startsWith('src/')) {
      return path.replace('src/', 'app/');
    }
    
    // Check if it looks like a component
    if (path.endsWith('.tsx') || path.endsWith('.jsx')) {
      // If it looks like a page (contains only one path segment or ends with Page)
      const fileName = path.split('/').pop() || '';
      if (fileName.toLowerCase().includes('page') || !path.includes('/')) {
        // Convert to Next.js page format
        const routeName = fileName.replace(/\.(tsx|jsx)$/, '').replace(/Page$/i, '').toLowerCase();
        return `app/${routeName}/page.tsx`;
      }
      // Otherwise treat as a component
      return `components/${path}`;
    }
    
    // Default: put in app directory
    return `app/${path}`;
  },
  
  componentExtension: '.tsx',
  
  // Templates
  componentTemplate: `'use client';

interface {{name}}Props {
  // Add props here
}

export default function {{name}}({ }: {{name}}Props) {
  return (
    <div className="p-4">
      <h1 className="text-2xl font-bold">{{name}}</h1>
    </div>
  );
}`,
  
  pageTemplate: `export default function {{name}}Page() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold">{{name}}</h1>
    </main>
  );
}`,
  
  apiRouteTemplate: `import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  return NextResponse.json({ message: 'Hello from {{name}}' });
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  return NextResponse.json({ received: body }, { status: 201 });
}

export async function PUT(request: NextRequest) {
  const body = await request.json();
  return NextResponse.json({ updated: body });
}

export async function DELETE(request: NextRequest) {
  return NextResponse.json({ deleted: true });
}`,
  
  // Capabilities
  supportsApiRoutes: true,
  supportsSSR: true,
  usesTypeScript: true
};

export default nextjsAppConfig;